# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{cui8tracks}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{hitode909}]
  s.date = %q{2011-10-17}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{hitode909@gmail.com}
  s.executables = [%q{cui8tracks.rb}]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/cui8tracks.rb",
    "lib/cui8tracks.rb",
    "lib/cui8tracks/api.rb",
    "lib/cui8tracks/cli.rb",
    "lib/cui8tracks/mix.rb",
    "lib/cui8tracks/session.rb",
    "lib/cui8tracks/set.rb",
    "lib/cui8tracks/thing.rb",
    "lib/cui8tracks/track.rb",
    "lib/cui8tracks/user.rb",
    "spec/cui8tracks_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/hitode909/cui8tracks}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/cui8tracks_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pit>, [">= 0"])
      s.add_runtime_dependency(%q<notify>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<pit>, [">= 0"])
      s.add_dependency(%q<notify>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<pit>, [">= 0"])
    s.add_dependency(%q<notify>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

